# Generated by Django 2.2.11 on 2021-05-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=45)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('meta_title', models.CharField(max_length=45)),
                ('meta_description', models.CharField(max_length=400)),
                ('meta_keywords', models.CharField(max_length=400)),
            ],
        ),
    ]
